# AG_action - Git Commit Action
name: git_commit
category: git
description: "Git 커밋 (메시지 자동 생성 옵션)"

triggers:
  - "커밋"
  - "git commit"
  - "변경사항 저장"

tags:
  - "git"
  - "version-control"

execution:
  type: hybrid  # Claude가 메시지 생성 가능

  working_dir: "."

  # 메시지가 없으면 Claude가 생성
  commands:
    - "git add -A"
    - "git commit -m '${message}'"

  timeout: 60
  retry: 0

params:
  - name: "message"
    type: string
    required: false
    description: "커밋 메시지 (없으면 Claude가 자동 생성)"

  - name: "auto_message"
    type: boolean
    required: false
    default: true
    description: "메시지 자동 생성"

  - name: "scope"
    type: string
    required: false
    description: "커밋 스코프 (feat, fix, docs, ...)"
    options: ["feat", "fix", "docs", "style", "refactor", "test", "chore"]

# Hybrid 실행 설정
hybrid:
  # message 파라미터가 없을 때 Claude CLI 호출
  condition: "not message"
  claude_task: |
    git diff --staged를 분석하고 Conventional Commits 형식으로 커밋 메시지 작성.
    형식: <type>(<scope>): <description>
    한국어로 작성.
  output_param: "message"

advanced:
  pre_check:
    - command: "git status --porcelain"
      expect_not_empty: true
      message: "커밋할 변경사항이 없습니다"

    - command: "git rev-parse --git-dir"
      expect_success: true
      message: "Git 저장소가 아닙니다"

  post_check:
    - command: "git log -1 --oneline"
      capture: "commit_hash"

  on_failure:
    notify: true
    suggest:
      - "git status로 상태 확인"

outputs:
  - name: "commit_hash"
    command: "git rev-parse HEAD"
    type: text

  - name: "commit_message"
    command: "git log -1 --format=%s"
    type: text
